### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by deriya-a** [deriya-a/furima--39154#21]
#### 自身のフリマアプリのURL：
https://furima-39154.onrender.com/
#### Basic認証のIDとパスワード：  
BASIC_AUTH_USER="admin" / BASIC_AUTH_PASSWORD="2222"
#### 出品者用のメールアドレスとパスワード：
aaa@aaa.com  / aaa111
#### 購入者用のメールアドレスとパスワード：
bbb@bbb.com / bbb111

よろしくお願いいたします。

**Comment by motomuun** [comment]
@deriya-a さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**商品出品機能の確認**

- [ ] **販売手数料と販売利益は、小数点以下を切り捨てて表示すること**
販売手数料と販売利益の計算式が異なっているようです。下記画像の場合、販売利益は300円になるかとおもいますので、ご確認の上修正をお願いします。
<img width="631" alt="スクリーンショット 2023-07-27 9 43 39" src="https://github.com/deriya-a/furima--39154/assets/65059944/e6cc4e5a-ef0b-4a84-be73-d5af3b898131">

**商品購入機能の確認**

- [ ] **クレジットカード情報は必須であり、PAY.JPテストカードの情報で決済ができること**
カード情報を入力するフォームに情報を入力することができません。入力出来るように修正をお願いします。

※購入後の機能に関しては動作確認ができていない為、次回ご提出時に併せて確認させていただきます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by deriya-a** [comment]
以下の本番環境での挙動確認をいたしました。
### 商品出品機能の確認
#### ・販売手数料と販売利益が正しく表示される
#### ・出品できる
#### ・出品商品を出品者が変更できる
#### ・出品商品を出品者が削除できる
#### ・出品者以外が商品の購入ができる

**Comment by shodai-ito** [comment]
@deriya-a さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [ ]  **商品出品時に登録した情報（商品名・商品画像・販売価格・配送料負担・商品説明・出品者名・カテゴリー・商品の状態・発送元の地域・発送日の目安）が、見本アプリと同様の形で出力されること**
詳細ページの画像のレイアウトが大きくい崩れているため、整えましょう。

- [ ] **issueに記載されたURLにアクセスし、同じくissueに記載されたIDとパスワードを入力すると、最終課題アプリ（FURIMA）が表示されること**
Basic認証が導入されておりませんでした。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by deriya-a** [comment]
Basic認証を導入致しました。
Basic認証の記述がコメントアウトされていたため、コメントアウトを解消し有効にしました。

**Comment by deriya-a** [comment]
詳細ページの画像のレイアウトを修正いたしました。

**Comment by motomuun** [comment]
@deriya-a さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)

**Comment by deriya-a** [comment]
達成要件を満たし、完了認定（LGTM）をいただいた。
